name: gdsc_bloc
description: A new Flutter project.

publish_to: "none"

version: 2.0.0+13

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  meta: ^1.9.1
  firebase: ^9.0.3
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  equatable: ^2.0.5
  shared_preferences: ^2.1.1
  google_sign_in: ^6.1.0
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  connectivity_plus: ^6.1.3
  animated_bottom_navigation_bar: ^1.2.0
  cloud_firestore: ^5.6.4
  carousel_slider: ^5.0.0
  dots_indicator: ^4.0.1
  cached_network_image: ^3.2.3
  intl: ^0.20.2
  lottie: ^3.0.0
  http: ^0.13.6
  googleapis_auth: ^1.4.0
  googleapis: ^13.1.0
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.4.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.3
  badges: ^3.1.1
  dropdown_button2: ^2.1.3
  photo_view: ^0.15.0
  dio: ^5.1.2
  path_provider: ^2.0.15
  awesome_notifications: ^0.10.1
  share_plus: ^10.1.4
  permission_handler: ^11.3.1
  gallery_saver: ^2.3.2
  grouped_list: ^6.0.0
  flutter_linkify: ^6.0.0
  firebase_messaging: ^15.2.3
  add_2_calendar: ^3.0.1
  flex_color_scheme: ^7.3.1
  auto_size_text: ^3.0.0
  flutter_local_notifications: ^18.0.1
  flutter_spinkit: ^5.2.0
  firebase_remote_config: ^5.4.1
  in_app_review: ^2.0.6
  hydrated_bloc: ^10.0.0

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  mocktail: ^1.0.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/logo.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/
    - shorebird.yaml
